"""SQLAlchemy ORM models.

Two schemas, one instance:
- ``app`` — everything the product owns (read/write via the app_rw role).
- ``analytics`` — the curated open datasets, reached only through the read-only
  ``datachat_exec`` role. The physical schema split is the second layer of the
  "no writes ever" defence (Schema §1, §5).

The models are the reference structure; the hand-written Alembic migrations are
the executable source of truth (roles/grants are security-critical and reviewed,
not autogenerated).
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Double,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.db.base import ANALYTICS_SCHEMA, APP_SCHEMA, EMBEDDING_DIM, Base


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(Uuid, primary_key=True, server_default=text("gen_random_uuid()"))


def _created_at() -> Mapped[datetime]:
    return mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)


# --- app schema ------------------------------------------------------------


class Conversation(Base):
    __tablename__ = "conversations"
    __table_args__ = (Index("ix_conversations_updated_at", "updated_at"), {"schema": APP_SCHEMA})

    id: Mapped[uuid.UUID] = _uuid_pk()
    title: Mapped[str] = mapped_column(Text, nullable=False)
    user_ref: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = _created_at()
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    turns: Mapped[list[Turn]] = relationship(
        back_populates="conversation", cascade="all, delete-orphan"
    )


class Turn(Base):
    __tablename__ = "turns"
    __table_args__ = (
        CheckConstraint("role in ('user','assistant')", name="role_valid"),
        Index("ix_turns_conversation_created", "conversation_id", "created_at"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.conversations.id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(String(16), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = _created_at()

    conversation: Mapped[Conversation] = relationship(back_populates="turns")


class Run(Base):
    __tablename__ = "runs"
    __table_args__ = (
        CheckConstraint(
            "status in ('running','awaiting_hitl','done','error','cancelled')",
            name="status_valid",
        ),
        Index("ix_runs_conversation_created", "conversation_id", "created_at"),
        Index("ix_runs_status", "status"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.conversations.id", ondelete="CASCADE"), nullable=False
    )
    turn_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.turns.id", ondelete="SET NULL"), nullable=True
    )
    status: Mapped[str] = mapped_column(String(24), nullable=False, server_default="running")
    provider_used: Mapped[str | None] = mapped_column(String(32), nullable=True)
    prompt_versions: Mapped[dict[str, str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    trace_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = _created_at()


class AgentActionRow(Base):
    __tablename__ = "agent_actions"
    __table_args__ = (
        Index("ix_agent_actions_run_created", "run_id", "created_at"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    run_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.runs.id", ondelete="CASCADE"), nullable=False
    )
    action_type: Mapped[str] = mapped_column(String(32), nullable=False)
    sql_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    decision: Mapped[str | None] = mapped_column(Text, nullable=True)
    row_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    elapsed_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = _created_at()


class DatasetRow(Base):
    __tablename__ = "datasets"
    __table_args__ = (
        UniqueConstraint("name", name="datasets_name"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    source: Mapped[str] = mapped_column(Text, nullable=False)
    version: Mapped[str] = mapped_column(Text, nullable=False)
    checksum: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, server_default="")
    loaded_at: Mapped[datetime] = _created_at()


class SemanticTable(Base):
    __tablename__ = "semantic_tables"
    __table_args__ = ({"schema": APP_SCHEMA},)

    id: Mapped[uuid.UUID] = _uuid_pk()
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.datasets.id", ondelete="CASCADE"), nullable=False
    )
    table_name: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)


class SemanticColumn(Base):
    __tablename__ = "semantic_columns"
    __table_args__ = (
        Index("ix_semantic_columns_table", "semantic_table_id"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    semantic_table_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.semantic_tables.id", ondelete="CASCADE"), nullable=False
    )
    column_name: Mapped[str] = mapped_column(Text, nullable=False)
    data_type: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    synonyms: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)


class FewShotExample(Base):
    __tablename__ = "few_shot_examples"
    __table_args__ = ({"schema": APP_SCHEMA},)

    id: Mapped[uuid.UUID] = _uuid_pk()
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.datasets.id", ondelete="CASCADE"), nullable=False
    )
    question: Mapped[str] = mapped_column(Text, nullable=False)
    sql: Mapped[str] = mapped_column(Text, nullable=False)
    tags: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)


class EvalCase(Base):
    __tablename__ = "eval_cases"
    __table_args__ = (
        Index("ix_eval_cases_dataset", "dataset_id"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    dataset_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.datasets.id", ondelete="CASCADE"), nullable=False
    )
    question: Mapped[str] = mapped_column(Text, nullable=False)
    gold_sql: Mapped[str] = mapped_column(Text, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)


class EvalRun(Base):
    __tablename__ = "eval_runs"
    __table_args__ = (
        Index("ix_eval_runs_created", "created_at"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    git_sha: Mapped[str] = mapped_column(String(64), nullable=False)
    execution_accuracy: Mapped[float] = mapped_column(Numeric(5, 4), nullable=False)
    faithfulness: Mapped[float] = mapped_column(Numeric(5, 4), nullable=False)
    guardrail_pass_rate: Mapped[float] = mapped_column(Numeric(5, 4), nullable=False)
    mlflow_run_id: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = _created_at()


class EvalCaseResult(Base):
    __tablename__ = "eval_case_results"
    __table_args__ = (
        Index("ix_eval_case_results_run", "eval_run_id"),
        {"schema": APP_SCHEMA},
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    eval_run_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.eval_runs.id", ondelete="CASCADE"), nullable=False
    )
    eval_case_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(f"{APP_SCHEMA}.eval_cases.id", ondelete="CASCADE"), nullable=False
    )
    passed: Mapped[bool] = mapped_column(nullable=False)
    predicted_sql: Mapped[str | None] = mapped_column(Text, nullable=True)
    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


# --- analytics schema (curated open data, read-only) -----------------------


class Country(Base):
    __tablename__ = "countries"
    __table_args__ = ({"schema": ANALYTICS_SCHEMA},)

    iso3: Mapped[str] = mapped_column(String(3), primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    region: Mapped[str | None] = mapped_column(Text, nullable=True)
    income_group: Mapped[str | None] = mapped_column(Text, nullable=True)


class WdiIndicator(Base):
    __tablename__ = "wdi_indicators"
    __table_args__ = ({"schema": ANALYTICS_SCHEMA},)

    indicator_code: Mapped[str] = mapped_column(Text, primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    unit: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)


class WdiValue(Base):
    __tablename__ = "wdi_values"
    __table_args__ = (
        Index("ix_wdi_values_indicator_year", "indicator_code", "year"),
        {"schema": ANALYTICS_SCHEMA},
    )

    country_iso3: Mapped[str] = mapped_column(
        String(3), ForeignKey(f"{ANALYTICS_SCHEMA}.countries.iso3"), primary_key=True
    )
    indicator_code: Mapped[str] = mapped_column(
        Text, ForeignKey(f"{ANALYTICS_SCHEMA}.wdi_indicators.indicator_code"), primary_key=True
    )
    year: Mapped[int] = mapped_column(Integer, primary_key=True)
    value: Mapped[float | None] = mapped_column(Double, nullable=True)


class OwidCo2(Base):
    __tablename__ = "owid_co2"
    __table_args__ = (
        Index("ix_owid_co2_country_year", "country_iso3", "year"),
        {"schema": ANALYTICS_SCHEMA},
    )

    country_iso3: Mapped[str] = mapped_column(
        String(3), ForeignKey(f"{ANALYTICS_SCHEMA}.countries.iso3"), primary_key=True
    )
    year: Mapped[int] = mapped_column(Integer, primary_key=True)
    co2: Mapped[float | None] = mapped_column(Double, nullable=True)
    co2_per_capita: Mapped[float | None] = mapped_column(Double, nullable=True)
    share_global_co2: Mapped[float | None] = mapped_column(Double, nullable=True)
