"""Render a finished answer as a downloadable report or CSV.

Pure functions over a plain dict (the cached answer payload) plus a provenance
list the caller resolves — no I/O, no infrastructure, so it's trivially testable.
"""

from __future__ import annotations

import csv
import io
from collections.abc import Sequence
from typing import Any


def build_csv(columns: Sequence[str], rows: Sequence[Sequence[object]]) -> str:
    """The result set as RFC-4180 CSV (proper quoting/escaping via the stdlib)."""
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(list(columns))
    for row in rows:
        writer.writerow(list(row))
    return buffer.getvalue()


def _markdown_table(columns: Sequence[str], rows: Sequence[Sequence[object]]) -> str:
    def _cell(value: object) -> str:
        return str(value).replace("|", "\\|")

    header = "| " + " | ".join(_cell(c) for c in columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = ["| " + " | ".join(_cell(v) for v in row) + " |" for row in rows]
    return "\n".join([header, divider, *body])


def build_markdown_report(
    payload: dict[str, Any], provenance: Sequence[tuple[str, str, str]]
) -> str:
    """Human-readable report: question, summary, SQL, data table, and sources.

    ``provenance`` is a list of ``(table, dataset_name, source_url)`` for the
    tables the query touched.
    """
    question = payload.get("question") or "DataChat report"
    execution = payload.get("execution") or {}
    columns = execution.get("columns", [])
    rows = execution.get("rows", [])
    sql = payload.get("sql") or ""
    explanation = payload.get("explanation") or "_No summary was produced._"

    sections = [
        f"# {question}",
        "",
        "## Summary",
        explanation,
        "",
        "## Query",
        "```sql",
        sql,
        "```",
        "",
        f"## Data ({execution.get('row_count', len(rows))} rows)",
        _markdown_table(columns, rows) if columns else "_No rows returned._",
    ]
    if provenance:
        sections += [
            "",
            "## Sources",
            "The full datasets are available from the original providers:",
        ]
        seen: set[str] = set()
        for _table, name, source in provenance:
            if name in seen:
                continue
            seen.add(name)
            sections.append(f"- **{name}** — [{source}]({source})")
    sections += ["", "---", "_Generated by DataChat._"]
    return "\n".join(sections) + "\n"
