"""Render a finished answer as a downloadable report or CSV.

Pure functions over a plain dict (the cached answer payload) plus a provenance
list the caller resolves — no I/O, no infrastructure, so it's trivially testable.
"""

from __future__ import annotations

import csv
import io
from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # keeps this module import-light and free of domain coupling at runtime
    from app.domain.entities import WebTable as WebTableLike
else:  # pragma: no cover - annotation-only alias
    WebTableLike = Any


def build_csv(columns: Sequence[str], rows: Sequence[Sequence[object]]) -> str:
    """The result set as RFC-4180 CSV (proper quoting/escaping via the stdlib)."""
    buffer = io.StringIO()
    writer = csv.writer(buffer)
    writer.writerow(list(columns))
    for row in rows:
        writer.writerow(list(row))
    return buffer.getvalue()


def _markdown_table(columns: Sequence[str], rows: Sequence[Sequence[object]]) -> str:
    def _cell(value: object) -> str:
        return str(value).replace("|", "\\|")

    header = "| " + " | ".join(_cell(c) for c in columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = ["| " + " | ".join(_cell(v) for v in row) + " |" for row in rows]
    return "\n".join([header, divider, *body])


def build_markdown_report(
    payload: dict[str, Any], provenance: Sequence[tuple[str, str, str]]
) -> str:
    """Human-readable report: question, summary, SQL, data table, and sources.

    ``provenance`` is a list of ``(table, dataset_name, source_url)`` for the
    tables the query touched.
    """
    question = payload.get("question") or "DataChat report"
    execution = payload.get("execution") or {}
    columns = execution.get("columns", [])
    rows = execution.get("rows", [])
    sql = payload.get("sql") or ""
    explanation = payload.get("explanation") or "_No summary was produced._"

    sections = [
        f"# {question}",
        "",
        "## Summary",
        explanation,
        "",
        "## Query",
        "```sql",
        sql,
        "```",
        "",
        f"## Data ({execution.get('row_count', len(rows))} rows)",
        _markdown_table(columns, rows) if columns else "_No rows returned._",
    ]
    if provenance:
        sections += [
            "",
            "## Sources",
            "The full datasets are available from the original providers:",
        ]
        seen: set[str] = set()
        for _table, name, source in provenance:
            if name in seen:
                continue
            seen.add(name)
            sections.append(f"- **{name}** — [{source}]({source})")
    sections += ["", "---", "_Generated by DataChat._"]
    return "\n".join(sections) + "\n"


def build_web_markdown_report(
    question: str,
    table: WebTableLike | None,
    explanation: str,
    sources: Sequence[tuple[str, str]],
) -> str:
    """Report for a web-sourced answer.

    Deliberately a different document from ``build_markdown_report``: no SQL
    section (there was no governed query), a provenance warning at the top, and a
    per-row source column so every figure is traceable to a link. ``sources`` is a
    list of ``(title, url)`` in the order the model saw them, so a row's
    ``source_index`` is a 1-based index into it.

    why a separate function rather than a flag: the two reports differ in what they
    are allowed to claim, and a shared renderer with a boolean is one wrong
    argument away from presenting scraped figures as verified data.
    """
    lines = [
        f"# {question}",
        "",
        "> **Web-sourced answer — not from the governed datasets.**",
        "> The figures below were read by a language model from public search"
        " results. They are attributed but *not* verified, and they did not pass"
        " the SQL guardrail. Check the linked sources before relying on them.",
        "",
        "## Summary",
        explanation or "_No summary was produced._",
    ]

    if table is not None and not table.is_empty():
        columns = [*table.columns, "Source"]
        rows = [
            [*(_blank_if_none(v) for v in row.values), f"[{row.source_index}]"]
            for row in table.rows
        ]
        lines += ["", f"## Data ({table.row_count} rows)", _markdown_table(columns, rows)]
        if table.caveat:
            lines += ["", f"_Caveat: {table.caveat}_"]
    else:
        lines += ["", "## Data", "_No table could be extracted from the sources._"]

    if sources:
        lines += ["", "## Sources"]
        lines += [f"{i}. [{title or url}]({url})" for i, (title, url) in enumerate(sources, 1)]

    lines += ["", "---", "_Generated by DataChat. Web-sourced; verify before use._"]
    return "\n".join(lines) + "\n"


def _blank_if_none(value: object) -> str:
    """A null means the sources did not say — render it as an explicit gap rather
    than the string 'None', which reads like data."""
    return "—" if value is None else str(value)
