"""Country names used only to *detect* an out-of-scope question.

This is a validation gazetteer, not data. Nothing here is queryable and nothing
here widens what the agent can answer — it exists so a question about a country
we did not load is recognised before any SQL is written, instead of producing a
confident empty answer. The loaded slice stays exactly 15 countries; see
``ingestion.definitions``.

why an explicit tuple rather than a whitespace-split block: the first version
split a text blob on spaces, which shredded "united states" into "united" and
"states". "states" then matched a question about the United States — a country we
*do* load — and refused it. Multi-word names have to survive intact, and matching
is whole-word longest-first.
"""

from __future__ import annotations

# ISO 3166-1 short names, lowercased. Not exhaustive by design: it covers the
# countries a visitor to a public demo plausibly asks about. A miss here is not a
# wrong answer, only a missed early exit — the question still falls through to
# the normal path and is caught by the emptiness check.
_NAMES: tuple[str, ...] = (
    "afghanistan",
    "albania",
    "algeria",
    "angola",
    "argentina",
    "armenia",
    "austria",
    "azerbaijan",
    "bahrain",
    "bangladesh",
    "belarus",
    "belgium",
    "bolivia",
    "bosnia",
    "botswana",
    "bulgaria",
    "cambodia",
    "cameroon",
    "chad",
    "chile",
    "colombia",
    "costa rica",
    "croatia",
    "cuba",
    "cyprus",
    "czechia",
    "czech republic",
    "denmark",
    "dominican republic",
    "ecuador",
    "egypt",
    "el salvador",
    "estonia",
    "ethiopia",
    "finland",
    "georgia",
    "ghana",
    "greece",
    "guatemala",
    "honduras",
    "hungary",
    "iceland",
    "indonesia",
    "iran",
    "iraq",
    "ireland",
    "israel",
    "italy",
    "ivory coast",
    "jamaica",
    "jordan",
    "kazakhstan",
    "kenya",
    "kuwait",
    "kyrgyzstan",
    "laos",
    "latvia",
    "lebanon",
    "libya",
    "lithuania",
    "luxembourg",
    "madagascar",
    "malawi",
    "malaysia",
    "mali",
    "malta",
    "mexico",
    "moldova",
    "mongolia",
    "montenegro",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nepal",
    "netherlands",
    "new zealand",
    "nicaragua",
    "niger",
    "north korea",
    "north macedonia",
    "norway",
    "oman",
    "pakistan",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "romania",
    "rwanda",
    "senegal",
    "serbia",
    "sierra leone",
    "singapore",
    "slovakia",
    "slovenia",
    "somalia",
    "south korea",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "tunisia",
    "turkey",
    "turkmenistan",
    "uganda",
    "ukraine",
    "uruguay",
    "uzbekistan",
    "venezuela",
    "vietnam",
    "yemen",
    "zambia",
    "zimbabwe",
)

ISO_3166_NAMES: frozenset[str] = frozenset(_NAMES)

# Colloquial forms mapped to the ISO name used in the loaded slice. Applied to
# the *loaded* set so that "USA" or "the UK" is recognised as in scope rather
# than treated as an unknown country.
ALIASES: dict[str, str] = {
    "usa": "united states",
    "u.s.": "united states",
    "u.s.a.": "united states",
    "america": "united states",
    "the us": "united states",
    "uk": "united kingdom",
    "u.k.": "united kingdom",
    "britain": "united kingdom",
    "great britain": "united kingdom",
    "england": "united kingdom",
    "russia": "russian federation",
    "south africa": "south africa",
    "saudi": "saudi arabia",
}
